CREATE DATABASE IF NOT EXISTS kopma_039
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'mhs_039'@'localhost'
IDENTIFIED BY 'PASSWORD_MHS';

GRANT ALL PRIVILEGES ON kopma_039.* TO 'mhs_039'@'localhost';